export const leads = [
  {
    id: '1',
    firstName: 'Marcus',
    lastName: 'Thompson',
    routing: 'HOT',
    score: 22,
    source: 'Zillow',
    loanType: 'Conventional',
    loanAmount: 485000,
    creditRange: '740–760',
    timeline: '30–60 days',
    employment: 'W-2 Employed',
    status: 'Qualified',
    lastContacted: '4 min ago',
    phone: '(555) 234-5678',
    email: 'marcus.t@email.com',
    brokerSummary:
      "Marcus is a highly qualified buyer with strong credit and stable W-2 income as a senior software engineer at a publicly traded tech company. He has an offer accepted and must close within 45 days — urgency is high. He's currently comparing rates with two other lenders, making speed and rate competitiveness the two critical factors.",
    talkingPoints: [
      "Pre-approved elsewhere at 7.1% — lead with your best rate immediately",
      "20% down payment eliminates PMI — use this as a differentiator vs competitors",
      "Ask about a 1-0 buydown — he mentioned wanting a lower monthly payment",
      "Tight 45-day closing window — emphasize your processing speed and dedicated team",
    ],
    flags: ["Shopping 2 other lenders — likely decides within 48 hours, act fast"],
    qualData: {
      'Loan Type': 'Conventional',
      'Loan Amount': '$485,000',
      'Credit Range': '740–760',
      'Timeline': '30–60 days',
      'Employment': 'W-2 / Senior Engineer',
      'Annual Income': '~$145,000',
      'Down Payment': '20% ($97,000)',
      'Property Type': 'Single Family',
    },
    conversation: [
      { from: 'ai', text: "Hi Marcus! I'm the virtual assistant for Apex Mortgage. You recently inquired about a home loan — mind if I ask a few quick questions to connect you with the right broker?", time: '10:02 AM' },
      { from: 'lead', text: 'Sure, go ahead', time: '10:03 AM' },
      { from: 'ai', text: 'Are you looking to purchase a new home, refinance, or something else?', time: '10:03 AM' },
      { from: 'lead', text: 'Purchase. I already have an offer accepted', time: '10:04 AM' },
      { from: 'ai', text: "Exciting! What's the purchase price and how much are you planning to put down?", time: '10:04 AM' },
      { from: 'lead', text: '$485k purchase, putting 20% down', time: '10:05 AM' },
      { from: 'ai', text: 'Do you know your approximate credit score?', time: '10:05 AM' },
      { from: 'lead', text: 'Around 750 last time I checked', time: '10:06 AM' },
      { from: 'ai', text: "Excellent — you're in great shape! What's your target closing date?", time: '10:06 AM' },
      { from: 'lead', text: 'End of next month, it\'s a firm deadline', time: '10:07 AM' },
      { from: 'ai', text: 'Got it. One last thing — are mornings or afternoons better for a broker to reach you?', time: '10:07 AM' },
      { from: 'lead', text: 'Mornings before 11am work best', time: '10:08 AM' },
    ],
    nurtureSequence: null,
    nurtureDay: null,
    nurtureTotal: null,
    lastMessageSent: null,
    nextMessageScheduled: null,
  },
  {
    id: '2',
    firstName: 'Sarah',
    lastName: 'Chen',
    routing: 'HOT',
    score: 21,
    source: 'Referral',
    loanType: 'Jumbo',
    loanAmount: 720000,
    creditRange: '760–780',
    timeline: '30–60 days',
    employment: 'W-2 Employed',
    status: 'Qualified',
    lastContacted: '22 min ago',
    phone: '(555) 876-4321',
    email: 'sarah.chen@email.com',
    brokerSummary:
      "Sarah is a physician referred by an existing client, with exceptional credit and high verified income. She's purchasing a second home in Scottsdale as an investment and has significant liquid assets for the down payment. She knows exactly what she wants and is ready to move quickly — the referring client relationship is on the line, so white-glove service is essential.",
    talkingPoints: [
      "Referred by your client Dr. Patel — mention this connection upfront to build immediate trust",
      "Jumbo loan at this credit tier qualifies for best-in-class rates — lead with specific numbers",
      "She's a physician — be concise and professional, she values efficiency over charm",
      "Mention physician loan programs — she may qualify for special terms with no PMI",
    ],
    flags: ["Referral relationship at stake — ensure the experience is exceptional from first contact"],
    qualData: {
      'Loan Type': 'Jumbo',
      'Loan Amount': '$720,000',
      'Credit Range': '760–780',
      'Timeline': '30–60 days',
      'Employment': 'W-2 / Physician',
      'Annual Income': '~$320,000',
      'Down Payment': '25% ($180,000)',
      'Property Type': 'Second Home / Investment',
    },
    conversation: [
      { from: 'ai', text: "Hi Sarah! Dr. Patel mentioned you'd be reaching out. I'm the assistant for Apex Mortgage — happy to get you connected quickly.", time: '9:41 AM' },
      { from: 'lead', text: "Yes, hi — I'm looking for a jumbo loan on a second property", time: '9:42 AM' },
      { from: 'ai', text: 'Is this for a primary residence or investment/second home?', time: '9:42 AM' },
      { from: 'lead', text: 'Second home and investment property in Scottsdale', time: '9:43 AM' },
      { from: 'ai', text: "What price range are you looking at and do you have a sense of the down payment?", time: '9:43 AM' },
      { from: 'lead', text: 'Around $720k, can do 25% down easily', time: '9:44 AM' },
      { from: 'ai', text: 'And your approximate credit score range?', time: '9:44 AM' },
      { from: 'lead', text: '770 or so', time: '9:45 AM' },
      { from: 'ai', text: "You're going to qualify for our very best jumbo rates. What's your target timeline to close?", time: '9:45 AM' },
      { from: 'lead', text: "Hoping to close in 45 days — I'm flexible but sooner is better", time: '9:46 AM' },
    ],
    nurtureSequence: null,
    nurtureDay: null,
    nurtureTotal: null,
    lastMessageSent: null,
    nextMessageScheduled: null,
  },
  {
    id: '3',
    firstName: 'David',
    lastName: 'Rodriguez',
    routing: 'WARM',
    score: 16,
    source: 'Facebook',
    loanType: 'FHA',
    loanAmount: 340000,
    creditRange: '680–700',
    timeline: '60–90 days',
    employment: 'W-2 Employed',
    status: 'Contacted',
    lastContacted: '2 hrs ago',
    phone: '(555) 345-6789',
    email: 'd.rodriguez@email.com',
    brokerSummary: null,
    talkingPoints: [],
    flags: [],
    qualData: {
      'Loan Type': 'FHA',
      'Loan Amount': '$340,000',
      'Credit Range': '680–700',
      'Timeline': '60–90 days',
      'Employment': 'W-2 / High School Teacher',
      'Down Payment': '3.5%',
      'Property Type': 'Single Family',
    },
    conversation: [
      { from: 'ai', text: "Hi David! I'm the assistant for Apex Mortgage. You expressed interest in a home loan — can I ask a few quick questions?", time: '2:15 PM' },
      { from: 'lead', text: 'Yeah sure', time: '2:18 PM' },
      { from: 'ai', text: 'Are you looking to purchase or refinance?', time: '2:18 PM' },
      { from: 'lead', text: 'Purchase, first time buyer', time: '2:22 PM' },
      { from: 'ai', text: "Exciting milestone! What price range are you looking at?", time: '2:22 PM' },
      { from: 'lead', text: 'Around 340k maybe', time: '2:35 PM' },
      { from: 'ai', text: "What's your approximate credit score?", time: '2:35 PM' },
      { from: 'lead', text: 'I think around 685', time: '2:47 PM' },
      { from: 'ai', text: "You qualify for FHA programs with great low down payment options. When are you hoping to move?", time: '2:47 PM' },
      { from: 'lead', text: 'Probably 2-3 months, still looking at neighborhoods', time: '3:02 PM' },
    ],
    nurtureSequence: 'First-Time Buyer',
    nurtureDay: 3,
    nurtureTotal: 7,
    lastMessageSent: 'Yesterday at 10:00 AM',
    nextMessageScheduled: 'Tomorrow at 10:00 AM',
  },
  {
    id: '4',
    firstName: 'Jennifer',
    lastName: 'Walsh',
    routing: 'WARM',
    score: 18,
    source: 'Zillow',
    loanType: 'Conventional',
    loanAmount: 615000,
    creditRange: '720–740',
    timeline: '60–90 days',
    employment: 'W-2 Employed',
    status: 'Contacted',
    lastContacted: '5 hrs ago',
    phone: '(555) 456-7890',
    email: 'j.walsh@email.com',
    brokerSummary: null,
    talkingPoints: [],
    flags: [],
    qualData: {
      'Loan Type': 'Conventional',
      'Loan Amount': '$615,000',
      'Credit Range': '720–740',
      'Timeline': '60–90 days',
      'Employment': 'W-2 / Travel Nurse',
      'Down Payment': '10–15%',
      'Property Type': 'Single Family',
    },
    conversation: [
      { from: 'ai', text: "Hi Jennifer! I saw you viewed some properties on Zillow. I'm with Apex Mortgage — can I help with financing questions?", time: '11:30 AM' },
      { from: 'lead', text: 'Hi! Yes I\'m looking to buy in the spring', time: '11:45 AM' },
      { from: 'ai', text: "Spring is a great time! What price range are you considering?", time: '11:45 AM' },
      { from: 'lead', text: 'Around $600–615k', time: '12:01 PM' },
      { from: 'ai', text: 'Are you a first-time buyer?', time: '12:01 PM' },
      { from: 'lead', text: "No I've owned before but sold in 2022 and have been renting", time: '12:15 PM' },
      { from: 'ai', text: 'Do you know your current credit score roughly?', time: '12:15 PM' },
      { from: 'lead', text: 'About 730', time: '12:32 PM' },
    ],
    nurtureSequence: 'Warm Buyer',
    nurtureDay: 5,
    nurtureTotal: 10,
    lastMessageSent: 'Today at 9:00 AM',
    nextMessageScheduled: 'Thursday at 9:00 AM',
  },
  {
    id: '5',
    firstName: 'Michael',
    lastName: 'Park',
    routing: 'WARM',
    score: 15,
    source: 'Website',
    loanType: 'Conventional',
    loanAmount: 290000,
    creditRange: '700–720',
    timeline: '90–120 days',
    employment: 'W-2 Employed',
    status: 'New',
    lastContacted: '1 day ago',
    phone: '(555) 567-8901',
    email: 'mpark.homes@email.com',
    brokerSummary: null,
    talkingPoints: [],
    flags: [],
    qualData: {
      'Loan Type': 'Conventional',
      'Loan Amount': '$290,000',
      'Credit Range': '700–720',
      'Timeline': '90–120 days',
      'Employment': 'W-2 / Firefighter',
      'Down Payment': '5–10%',
      'Property Type': 'Condo / Townhome',
    },
    conversation: [
      { from: 'ai', text: "Hi Michael! Thanks for reaching out to Apex Mortgage. Are you looking to purchase, refinance, or just exploring?", time: '3:55 PM' },
      { from: 'lead', text: 'Looking to purchase, first time buyer', time: '4:10 PM' },
      { from: 'ai', text: 'Exciting milestone! What price range are you thinking?', time: '4:10 PM' },
      { from: 'lead', text: 'Under 300k, maybe a condo or townhome', time: '4:28 PM' },
      { from: 'ai', text: "Good call — lots of great options there. What's your timeline for moving?", time: '4:28 PM' },
      { from: 'lead', text: 'Probably 3-4 months, still saving a bit more', time: '4:45 PM' },
      { from: 'ai', text: "Do you have a sense of your credit score?", time: '4:45 PM' },
      { from: 'lead', text: 'I think around 710', time: '5:02 PM' },
    ],
    nurtureSequence: 'First-Time Buyer',
    nurtureDay: 1,
    nurtureTotal: 7,
    lastMessageSent: 'Yesterday at 2:00 PM',
    nextMessageScheduled: 'Tomorrow at 2:00 PM',
  },
  {
    id: '6',
    firstName: 'Lisa',
    lastName: 'Nguyen',
    routing: 'WARM',
    score: 17,
    source: 'Referral',
    loanType: 'Conventional',
    loanAmount: 520000,
    creditRange: '710–730',
    timeline: '60–90 days',
    employment: 'W-2 Employed',
    status: 'Contacted',
    lastContacted: '3 hrs ago',
    phone: '(555) 678-9012',
    email: 'lisa.n@email.com',
    brokerSummary: null,
    talkingPoints: [],
    flags: [],
    qualData: {
      'Loan Type': 'Conventional',
      'Loan Amount': '$520,000',
      'Credit Range': '710–730',
      'Timeline': '60–90 days',
      'Employment': 'W-2 / Sr. Accountant',
      'Down Payment': '15%',
      'Property Type': 'Single Family',
    },
    conversation: [
      { from: 'ai', text: "Hi Lisa! A colleague mentioned you might be looking to buy — I'm with Apex Mortgage and happy to help!", time: '1:00 PM' },
      { from: 'lead', text: 'Yes, relocating for work and need to buy relatively quickly', time: '1:05 PM' },
      { from: 'ai', text: 'Understood! What price range are you targeting?', time: '1:05 PM' },
      { from: 'lead', text: 'Around $520k', time: '1:08 PM' },
      { from: 'ai', text: "Do you know your credit score and how much you plan to put down?", time: '1:08 PM' },
      { from: 'lead', text: '720 credit score, can do 15% down', time: '1:12 PM' },
      { from: 'ai', text: "Great position! What's your start date at the new job?", time: '1:12 PM' },
      { from: 'lead', text: 'Starting in 8 weeks, want to be moved in by then ideally', time: '1:18 PM' },
    ],
    nurtureSequence: 'Relocation Buyer',
    nurtureDay: 2,
    nurtureTotal: 5,
    lastMessageSent: 'Today at 8:00 AM',
    nextMessageScheduled: 'Tomorrow at 8:00 AM',
  },
  {
    id: '7',
    firstName: 'Robert',
    lastName: 'Garcia',
    routing: 'COLD',
    score: 9,
    source: 'Facebook',
    loanType: 'FHA',
    loanAmount: 380000,
    creditRange: '620–640',
    timeline: '6+ months',
    employment: 'W-2 Employed',
    status: 'Contacted',
    lastContacted: '2 days ago',
    phone: '(555) 789-0123',
    email: 'rgarcia@email.com',
    brokerSummary: null,
    talkingPoints: [],
    flags: [],
    qualData: {
      'Loan Type': 'FHA',
      'Loan Amount': '$380,000',
      'Credit Range': '620–640',
      'Timeline': '6+ months',
      'Employment': 'W-2 / Warehouse Manager',
      'Down Payment': '3.5%',
      'Property Type': 'Single Family',
    },
    conversation: [
      { from: 'ai', text: "Hi Robert! Thanks for your interest in Apex Mortgage. Are you looking to purchase or refinance?", time: '4:30 PM' },
      { from: 'lead', text: 'Purchase eventually, not sure when', time: '5:15 PM' },
      { from: 'ai', text: "That's totally fine — we can help you plan ahead! What price range are you thinking?", time: '5:15 PM' },
      { from: 'lead', text: 'Around 380k but I need to work on my credit first', time: '6:02 PM' },
      { from: 'ai', text: "Smart approach! What's your current credit score?", time: '6:02 PM' },
      { from: 'lead', text: 'Around 625, trying to get it up', time: '6:45 PM' },
    ],
    nurtureSequence: 'Credit Builder',
    nurtureDay: 6,
    nurtureTotal: 14,
    lastMessageSent: '2 days ago',
    nextMessageScheduled: 'Tomorrow',
  },
  {
    id: '8',
    firstName: 'Amanda',
    lastName: 'Foster',
    routing: 'COLD',
    score: 11,
    source: 'Zillow',
    loanType: 'Conventional',
    loanAmount: 445000,
    creditRange: '650–670',
    timeline: '4–6 months',
    employment: 'Self-Employed',
    status: 'Contacted',
    lastContacted: '3 days ago',
    phone: '(555) 890-1234',
    email: 'amanda.f@email.com',
    brokerSummary: null,
    talkingPoints: [],
    flags: [],
    qualData: {
      'Loan Type': 'Conventional',
      'Loan Amount': '$445,000',
      'Credit Range': '650–670',
      'Timeline': '4–6 months',
      'Employment': 'Self-Employed / Freelancer',
      'Down Payment': '10%',
      'Property Type': 'Single Family',
    },
    conversation: [
      { from: 'ai', text: "Hi Amanda! I'm the assistant for Apex Mortgage. Are you looking to purchase a home?", time: '10:15 AM' },
      { from: 'lead', text: "Maybe, just browsing to see what I can afford", time: '11:30 AM' },
      { from: 'ai', text: "Happy to help you figure that out! What price range interests you?", time: '11:30 AM' },
      { from: 'lead', text: "Something around $445k but I'm self employed which I heard is harder", time: '12:05 PM' },
      { from: 'ai', text: "Self-employed loans are definitely doable — what's your approximate credit score?", time: '12:05 PM' },
      { from: 'lead', text: 'Around 660 I think', time: '1:00 PM' },
    ],
    nurtureSequence: 'Self-Employed Buyer',
    nurtureDay: 4,
    nurtureTotal: 10,
    lastMessageSent: '3 days ago',
    nextMessageScheduled: 'Today at 3:00 PM',
  },
  {
    id: '9',
    firstName: 'James',
    lastName: 'Williams',
    routing: 'COLD',
    score: 7,
    source: 'Website',
    loanType: 'FHA',
    loanAmount: 310000,
    creditRange: '600–620',
    timeline: '6+ months',
    employment: 'W-2 Employed',
    status: 'New',
    lastContacted: '4 days ago',
    phone: '(555) 901-2345',
    email: 'jwilliams@email.com',
    brokerSummary: null,
    talkingPoints: [],
    flags: [],
    qualData: {
      'Loan Type': 'FHA',
      'Loan Amount': '$310,000',
      'Credit Range': '600–620',
      'Timeline': '6+ months',
      'Employment': 'W-2 / Retail Manager',
      'Down Payment': '3.5%',
      'Property Type': 'Single Family',
    },
    conversation: [
      { from: 'ai', text: "Hi James! Thanks for reaching out to Apex Mortgage. What type of loan are you interested in?", time: '6:20 PM' },
      { from: 'lead', text: "Not sure, never bought a house before", time: '7:45 PM' },
      { from: 'ai', text: "No problem — we'll walk you through it! What price range are you thinking?", time: '7:45 PM' },
      { from: 'lead', text: 'Around 310k', time: '8:10 PM' },
      { from: 'ai', text: "Do you know your credit score roughly?", time: '8:10 PM' },
      { from: 'lead', text: 'Probably around 610, not great I know', time: '8:35 PM' },
    ],
    nurtureSequence: 'Credit Builder',
    nurtureDay: 2,
    nurtureTotal: 14,
    lastMessageSent: '4 days ago',
    nextMessageScheduled: 'Tomorrow',
  },
  {
    id: '10',
    firstName: 'Patricia',
    lastName: 'Kim',
    routing: 'COLD',
    score: 13,
    source: 'Referral',
    loanType: 'Jumbo',
    loanAmount: 675000,
    creditRange: '690–710',
    timeline: '6+ months',
    employment: 'W-2 Employed',
    status: 'Contacted',
    lastContacted: '1 day ago',
    phone: '(555) 012-3456',
    email: 'p.kim@email.com',
    brokerSummary: null,
    talkingPoints: [],
    flags: [],
    qualData: {
      'Loan Type': 'Jumbo',
      'Loan Amount': '$675,000',
      'Credit Range': '690–710',
      'Timeline': '6+ months',
      'Employment': 'W-2 / Marketing Director',
      'Down Payment': '20%',
      'Property Type': 'Single Family',
    },
    conversation: [
      { from: 'ai', text: "Hi Patricia! I'm with Apex Mortgage. Are you looking to purchase a home?", time: '2:00 PM' },
      { from: 'lead', text: "Yes eventually — we're not quite ready yet but want to start learning", time: '2:45 PM' },
      { from: 'ai', text: "Smart to plan ahead! What price range are you thinking?", time: '2:45 PM' },
      { from: 'lead', text: 'Around 675k, we want something nice in a good school district', time: '3:10 PM' },
      { from: 'ai', text: "Beautiful range. What's your approximate credit score?", time: '3:10 PM' },
      { from: 'lead', text: 'Around 700', time: '3:30 PM' },
    ],
    nurtureSequence: 'Long-Term Buyer',
    nurtureDay: 3,
    nurtureTotal: 21,
    lastMessageSent: '1 day ago',
    nextMessageScheduled: 'Friday',
  },
  {
    id: '11',
    firstName: 'Kevin',
    lastName: "O'Brien",
    routing: 'COLD',
    score: 10,
    source: 'Facebook',
    loanType: 'Conventional',
    loanAmount: 285000,
    creditRange: '660–680',
    timeline: '4–6 months',
    employment: 'W-2 Employed',
    status: 'New',
    lastContacted: '5 days ago',
    phone: '(555) 123-4567',
    email: 'kevin.ob@email.com',
    brokerSummary: null,
    talkingPoints: [],
    flags: [],
    qualData: {
      'Loan Type': 'Conventional',
      'Loan Amount': '$285,000',
      'Credit Range': '660–680',
      'Timeline': '4–6 months',
      'Employment': 'W-2 / New Job (2 months)',
      'Down Payment': '5–10%',
      'Property Type': 'Condo',
    },
    conversation: [
      { from: 'ai', text: "Hi Kevin! Thanks for your interest in Apex Mortgage. Are you looking to buy a home?", time: '5:00 PM' },
      { from: 'lead', text: "Yeah looking around 285k, just started a new job though", time: '5:20 PM' },
      { from: 'ai', text: "Congrats on the new job! How long have you been in your current role?", time: '5:20 PM' },
      { from: 'lead', text: 'Only 2 months, is that a problem?', time: '5:35 PM' },
      { from: 'ai', text: "It can affect some loan programs, but we have options. What's your credit score roughly?", time: '5:35 PM' },
      { from: 'lead', text: 'Around 670', time: '5:52 PM' },
    ],
    nurtureSequence: 'Warm Buyer',
    nurtureDay: 7,
    nurtureTotal: 10,
    lastMessageSent: '5 days ago',
    nextMessageScheduled: 'Today at 5:00 PM',
  },
  {
    id: '12',
    firstName: 'Diana',
    lastName: 'Martinez',
    routing: 'COLD',
    score: 12,
    source: 'Website',
    loanType: 'Conventional',
    loanAmount: 540000,
    creditRange: '680–700',
    timeline: '3–4 months',
    employment: 'Self-Employed',
    status: 'Contacted',
    lastContacted: '2 days ago',
    phone: '(555) 234-5670',
    email: 'diana.m@email.com',
    brokerSummary: null,
    talkingPoints: [],
    flags: [],
    qualData: {
      'Loan Type': 'Conventional',
      'Loan Amount': '$540,000',
      'Credit Range': '680–700',
      'Timeline': '3–4 months',
      'Employment': 'Self-Employed / Business Owner',
      'Down Payment': '20%',
      'Property Type': 'Single Family',
    },
    conversation: [
      { from: 'ai', text: "Hi Diana! I'm the assistant for Apex Mortgage. What type of loan are you looking for?", time: '9:00 AM' },
      { from: 'lead', text: "Purchase loan — I own a business so I'm self-employed", time: '9:22 AM' },
      { from: 'ai', text: "Great — self-employed loans are a specialty of ours. What's the purchase price?", time: '9:22 AM' },
      { from: 'lead', text: 'Around $540k', time: '9:35 AM' },
      { from: 'ai', text: "And your approximate credit score?", time: '9:35 AM' },
      { from: 'lead', text: 'Around 690 I think', time: '9:50 AM' },
      { from: 'ai', text: "Solid. Do you have 2 years of business tax returns available?", time: '9:50 AM' },
      { from: 'lead', text: "Yes, business has been running 5 years", time: '10:02 AM' },
    ],
    nurtureSequence: 'Self-Employed Buyer',
    nurtureDay: 8,
    nurtureTotal: 10,
    lastMessageSent: '2 days ago',
    nextMessageScheduled: 'Tomorrow',
  },
];

export const activityEvents = [
  {
    id: '1',
    type: 'qualified',
    icon: '⚡',
    text: 'Marcus Thompson qualified as HOT',
    subtext: 'Score: 22/24 · Zillow · Conventional $485k',
    time: '4 min ago',
    routing: 'HOT',
  },
  {
    id: '2',
    type: 'reply',
    icon: '💬',
    text: 'Sarah Chen replied to AI qualification',
    subtext: 'Referral · Jumbo $720k · Score 21/24',
    time: '22 min ago',
    routing: 'HOT',
  },
  {
    id: '3',
    type: 'nurture',
    icon: '📧',
    text: 'Nurture message sent to Jennifer Walsh',
    subtext: 'Day 5 of 10 — Warm Buyer sequence',
    time: '1 hr ago',
    routing: 'WARM',
  },
  {
    id: '4',
    type: 'upgrade',
    icon: '📈',
    text: "Kevin O'Brien upgraded COLD → WARM",
    subtext: 'Replied to Day 7 of Warm Buyer sequence',
    time: '2 hrs ago',
    routing: 'WARM',
  },
  {
    id: '5',
    type: 'reply',
    icon: '💬',
    text: 'Amanda Foster replied to nurture message',
    subtext: 'Day 4 of 10 — Self-Employed Buyer sequence',
    time: '3 hrs ago',
    routing: 'COLD',
  },
  {
    id: '6',
    type: 'new',
    icon: '✨',
    text: 'New lead: Diana Martinez submitted',
    subtext: 'Website · Conventional $540k · Self-Employed',
    time: '5 hrs ago',
    routing: null,
  },
  {
    id: '7',
    type: 'booked',
    icon: '📅',
    text: 'Patricia Kim booked a discovery call for Friday',
    subtext: 'Long-Term Buyer sequence · Jumbo $675k',
    time: 'Yesterday',
    routing: 'COLD',
  },
  {
    id: '8',
    type: 'nurture',
    icon: '📧',
    text: 'Nurture message sent to Robert Garcia',
    subtext: 'Day 6 of 14 — Credit Builder sequence',
    time: 'Yesterday',
    routing: 'COLD',
  },
  {
    id: '9',
    type: 'new',
    icon: '✨',
    text: 'New lead: Michael Park submitted',
    subtext: 'Website · Conventional $290k · First-Time Buyer',
    time: 'Yesterday',
    routing: null,
  },
  {
    id: '10',
    type: 'qualified',
    icon: '⚡',
    text: 'Lisa Nguyen qualified as WARM',
    subtext: 'Score: 17/24 · Referral · Conventional $520k',
    time: '2 days ago',
    routing: 'WARM',
  },
];
